package quicktime

type StorefrontInfo struct {
	Name         string
	CountryCode  string
	StorefrontID int
}

// Storefront Code and ID
// 	https://www.apple.com/itunesaffiliates/US/2009/Document/LinktoiTune.pdf
// 	https://web.archive.org/web/20191206001952/https://affiliate.itunes.apple.com/resources/documentation/linking-to-the-itunes-music-store/
// 	https://github.com/MrBukLau/mp3tag-web-sources-scripts/blob/main/Information/iTunes%20Country%20Codes%20and%20Storefront%20IDs.csv
// 	https://api.music.apple.com/v1/storefronts

var StorefrontTable = []StorefrontInfo{
	{Name: "Algeria", CountryCode: "dz", StorefrontID: 143563},
	{Name: "Angola", CountryCode: "ao", StorefrontID: 143564},
	{Name: "Anguilla", CountryCode: "ai", StorefrontID: 143538},
	{Name: "Antigua and Barbuda", CountryCode: "ag", StorefrontID: 143540},
	{Name: "Argentina", CountryCode: "ar", StorefrontID: 143505},
	{Name: "Armenia", CountryCode: "am", StorefrontID: 143524},
	{Name: "Australia", CountryCode: "au", StorefrontID: 143460},
	{Name: "Austria", CountryCode: "at", StorefrontID: 143445},
	{Name: "Azerbaijan", CountryCode: "az", StorefrontID: 143568},
	{Name: "Bahamas", CountryCode: "bs", StorefrontID: 143539},
	{Name: "Bahrain", CountryCode: "bh", StorefrontID: 143559},
	{Name: "Barbados", CountryCode: "bb", StorefrontID: 143541},
	{Name: "Belarus", CountryCode: "by", StorefrontID: 143565},
	{Name: "Belgium", CountryCode: "be", StorefrontID: 143446},
	{Name: "Belize", CountryCode: "bz", StorefrontID: 143555},
	{Name: "Benin", CountryCode: "bj", StorefrontID: 143576},
	{Name: "Bermuda", CountryCode: "bm", StorefrontID: 143542},
	{Name: "Bhutan", CountryCode: "bt", StorefrontID: 143577},
	{Name: "Bolivia", CountryCode: "bo", StorefrontID: 143556},
	{Name: "Bosnia and Herzegovina", CountryCode: "ba", StorefrontID: 143612},
	{Name: "Botswana", CountryCode: "bw", StorefrontID: 143525},
	{Name: "Brazil", CountryCode: "br", StorefrontID: 143503},
	{Name: "British Virgin Islands", CountryCode: "vg", StorefrontID: 143543},
	{Name: "Bulgaria", CountryCode: "bg", StorefrontID: 143526},
	{Name: "Cambodia", CountryCode: "kh", StorefrontID: 143579},
	{Name: "Cameroon", CountryCode: "cm", StorefrontID: 143574},
	{Name: "Canada", CountryCode: "ca", StorefrontID: 143455},
	{Name: "Cape Verde", CountryCode: "cv", StorefrontID: 143580},
	{Name: "Cayman Islands", CountryCode: "ky", StorefrontID: 143544},
	{Name: "Chad", CountryCode: "td", StorefrontID: 143581},
	{Name: "Chile", CountryCode: "cl", StorefrontID: 143483},
	{Name: "China mainland", CountryCode: "cn", StorefrontID: 143465},
	{Name: "Colombia", CountryCode: "co", StorefrontID: 143501},
	{Name: "Costa Rica", CountryCode: "cr", StorefrontID: 143495},
	{Name: "Croatia", CountryCode: "hr", StorefrontID: 143494},
	{Name: "Cyprus", CountryCode: "cy", StorefrontID: 143557},
	{Name: "Czech Republic", CountryCode: "cz", StorefrontID: 143489},
	{Name: "Côte d'Ivoire", CountryCode: "ci", StorefrontID: 143527},
	{Name: "Democratic Republic of the Congo", CountryCode: "cd", StorefrontID: 143613},
	{Name: "Denmark", CountryCode: "dk", StorefrontID: 143458},
	{Name: "Dominica", CountryCode: "dm", StorefrontID: 143545},
	{Name: "Dominican Republic", CountryCode: "do", StorefrontID: 143508},
	{Name: "Ecuador", CountryCode: "ec", StorefrontID: 143509},
	{Name: "Egypt", CountryCode: "eg", StorefrontID: 143516},
	{Name: "El Salvador", CountryCode: "sv", StorefrontID: 143506},
	{Name: "Estonia", CountryCode: "ee", StorefrontID: 143518},
	{Name: "Eswatini", CountryCode: "sz", StorefrontID: 143602},
	{Name: "Fiji", CountryCode: "fj", StorefrontID: 143583},
	{Name: "Finland", CountryCode: "fi", StorefrontID: 143447},
	{Name: "France", CountryCode: "fr", StorefrontID: 143442},
	{Name: "Gabon", CountryCode: "ga", StorefrontID: 143614},
	{Name: "Gambia", CountryCode: "gm", StorefrontID: 143584},
	{Name: "Georgia", CountryCode: "ge", StorefrontID: -1},
	{Name: "Germany", CountryCode: "de", StorefrontID: 143443},
	{Name: "Ghana", CountryCode: "gh", StorefrontID: 143573},
	{Name: "Greece", CountryCode: "gr", StorefrontID: 143448},
	{Name: "Grenada", CountryCode: "gd", StorefrontID: 143546},
	{Name: "Guatemala", CountryCode: "gt", StorefrontID: 143504},
	{Name: "Guinea-Bissau", CountryCode: "gw", StorefrontID: 143585},
	{Name: "Guyana", CountryCode: "gy", StorefrontID: 143553},
	{Name: "Honduras", CountryCode: "hn", StorefrontID: 143510},
	{Name: "Hong Kong", CountryCode: "hk", StorefrontID: 143463},
	{Name: "Hungary", CountryCode: "hu", StorefrontID: 143482},
	{Name: "Iceland", CountryCode: "is", StorefrontID: 143558},
	{Name: "India", CountryCode: "in", StorefrontID: 143467},
	{Name: "Indonesia", CountryCode: "id", StorefrontID: 143476},
	{Name: "Iraq", CountryCode: "iq", StorefrontID: 143617},
	{Name: "Ireland", CountryCode: "ie", StorefrontID: 143449},
	{Name: "Israel", CountryCode: "il", StorefrontID: 143491},
	{Name: "Italy", CountryCode: "it", StorefrontID: 143450},
	{Name: "Jamaica", CountryCode: "jm", StorefrontID: 143511},
	{Name: "Japan", CountryCode: "jp", StorefrontID: 143462},
	{Name: "Jordan", CountryCode: "jo", StorefrontID: 143528},
	{Name: "Kazakhstan", CountryCode: "kz", StorefrontID: 143517},
	{Name: "Kenya", CountryCode: "ke", StorefrontID: 143529},
	{Name: "Korea, Republic of", CountryCode: "kr", StorefrontID: 143466},
	{Name: "Kosovo", CountryCode: "xk", StorefrontID: 143624},
	{Name: "Kuwait", CountryCode: "kw", StorefrontID: 143493},
	{Name: "Kyrgyzstan", CountryCode: "kg", StorefrontID: 143586},
	{Name: "Lao People's Democratic Republic", CountryCode: "la", StorefrontID: 143587},
	{Name: "Latvia", CountryCode: "lv", StorefrontID: 143519},
	{Name: "Lebanon", CountryCode: "lb", StorefrontID: 143497},
	{Name: "Liberia", CountryCode: "lr", StorefrontID: 143588},
	{Name: "Libya", CountryCode: "ly", StorefrontID: 143567},
	{Name: "Lithuania", CountryCode: "lt", StorefrontID: 143520},
	{Name: "Luxembourg", CountryCode: "lu", StorefrontID: 143451},
	{Name: "Macao", CountryCode: "mo", StorefrontID: 143515},
	{Name: "Madagascar", CountryCode: "mg", StorefrontID: 143531},
	{Name: "Malawi", CountryCode: "mw", StorefrontID: 143589},
	{Name: "Malaysia", CountryCode: "my", StorefrontID: 143473},
	{Name: "Maldives", CountryCode: "mv", StorefrontID: 143488},
	{Name: "Mali", CountryCode: "ml", StorefrontID: 143532},
	{Name: "Malta", CountryCode: "mt", StorefrontID: 143521},
	{Name: "Mauritania", CountryCode: "mr", StorefrontID: 143590},
	{Name: "Mauritius", CountryCode: "mu", StorefrontID: 143533},
	{Name: "Mexico", CountryCode: "mx", StorefrontID: 143468},
	{Name: "Micronesia, Federated States of", CountryCode: "fm", StorefrontID: 143591},
	{Name: "Moldova", CountryCode: "md", StorefrontID: 143523},
	{Name: "Mongolia", CountryCode: "mn", StorefrontID: 143592},
	{Name: "Montenegro", CountryCode: "me", StorefrontID: 143619},
	{Name: "Montserrat", CountryCode: "ms", StorefrontID: 143547},
	{Name: "Morocco", CountryCode: "ma", StorefrontID: 143620},
	{Name: "Mozambique", CountryCode: "mz", StorefrontID: 143593},
	{Name: "Myanmar", CountryCode: "mm", StorefrontID: 143570},
	{Name: "Namibia", CountryCode: "na", StorefrontID: 143594},
	{Name: "Nepal", CountryCode: "np", StorefrontID: 143484},
	{Name: "Netherlands", CountryCode: "nl", StorefrontID: 143452},
	{Name: "New Zealand", CountryCode: "nz", StorefrontID: 143461},
	{Name: "Nicaragua", CountryCode: "ni", StorefrontID: 143512},
	{Name: "Niger", CountryCode: "ne", StorefrontID: 143534},
	{Name: "Nigeria", CountryCode: "ng", StorefrontID: 143561},
	{Name: "North Macedonia", CountryCode: "mk", StorefrontID: 143530},
	{Name: "Norway", CountryCode: "no", StorefrontID: 143457},
	{Name: "Oman", CountryCode: "om", StorefrontID: 143562},
	{Name: "Panama", CountryCode: "pa", StorefrontID: 143485},
	{Name: "Papua New Guinea", CountryCode: "pg", StorefrontID: 143597},
	{Name: "Paraguay", CountryCode: "py", StorefrontID: 143513},
	{Name: "Peru", CountryCode: "pe", StorefrontID: 143507},
	{Name: "Philippines", CountryCode: "ph", StorefrontID: 143474},
	{Name: "Poland", CountryCode: "pl", StorefrontID: 143478},
	{Name: "Portugal", CountryCode: "pt", StorefrontID: 143453},
	{Name: "Qatar", CountryCode: "qa", StorefrontID: 143498},
	{Name: "Republic of the Congo", CountryCode: "cg", StorefrontID: 143582},
	{Name: "Romania", CountryCode: "ro", StorefrontID: 143487},
	{Name: "Russia", CountryCode: "ru", StorefrontID: 143469},
	{Name: "Rwanda", CountryCode: "rw", StorefrontID: 143621},
	{Name: "Saudi Arabia", CountryCode: "sa", StorefrontID: 143479},
	{Name: "Senegal", CountryCode: "sn", StorefrontID: 143535},
	{Name: "Serbia", CountryCode: "rs", StorefrontID: 143500},
	{Name: "Seychelles", CountryCode: "sc", StorefrontID: 143599},
	{Name: "Sierra Leone", CountryCode: "sl", StorefrontID: 143600},
	{Name: "Singapore", CountryCode: "sg", StorefrontID: 143464},
	{Name: "Slovakia", CountryCode: "sk", StorefrontID: 143496},
	{Name: "Slovenia", CountryCode: "si", StorefrontID: 143499},
	{Name: "Solomon Islands", CountryCode: "sb", StorefrontID: 143601},
	{Name: "South Africa", CountryCode: "za", StorefrontID: 143472},
	{Name: "Spain", CountryCode: "es", StorefrontID: 143454},
	{Name: "Sri Lanka", CountryCode: "lk", StorefrontID: 143486},
	{Name: "St. Kitts and Nevis", CountryCode: "kn", StorefrontID: 143548},
	{Name: "St. Lucia", CountryCode: "lc", StorefrontID: 143549},
	{Name: "St. Vincent and The Grenadines", CountryCode: "vc", StorefrontID: 143550},
	{Name: "Suriname", CountryCode: "sr", StorefrontID: 143554},
	{Name: "Sweden", CountryCode: "se", StorefrontID: 143456},
	{Name: "Switzerland", CountryCode: "ch", StorefrontID: 143459},
	{Name: "Taiwan", CountryCode: "tw", StorefrontID: 143470},
	{Name: "Tajikistan", CountryCode: "tj", StorefrontID: 143603},
	{Name: "Tanzania", CountryCode: "tz", StorefrontID: 143572},
	{Name: "Thailand", CountryCode: "th", StorefrontID: 143475},
	{Name: "Tonga", CountryCode: "to", StorefrontID: 143608},
	{Name: "Trinidad and Tobago", CountryCode: "tt", StorefrontID: 143551},
	{Name: "Tunisia", CountryCode: "tn", StorefrontID: 143536},
	{Name: "Turkmenistan", CountryCode: "tm", StorefrontID: 143604},
	{Name: "Turks and Caicos", CountryCode: "tc", StorefrontID: 143552},
	{Name: "Türkiye", CountryCode: "tr", StorefrontID: 143480},
	{Name: "UAE", CountryCode: "ae", StorefrontID: 143481},
	{Name: "Uganda", CountryCode: "ug", StorefrontID: 143537},
	{Name: "Ukraine", CountryCode: "ua", StorefrontID: 143492},
	{Name: "United Kingdom", CountryCode: "gb", StorefrontID: 143444},
	{Name: "United States", CountryCode: "us", StorefrontID: 143441},
	{Name: "Uruguay", CountryCode: "uy", StorefrontID: 143514},
	{Name: "Uzbekistan", CountryCode: "uz", StorefrontID: 143566},
	{Name: "Vanuatu", CountryCode: "vu", StorefrontID: 143609},
	{Name: "Venezuela", CountryCode: "ve", StorefrontID: 143502},
	{Name: "Vietnam", CountryCode: "vn", StorefrontID: 143471},
	{Name: "Yemen", CountryCode: "ye", StorefrontID: 143571},
	{Name: "Zambia", CountryCode: "zm", StorefrontID: 143622},
	{Name: "Zimbabwe", CountryCode: "zw", StorefrontID: 143605},
}

func GetStorefrontID(code string) int {
	for _, info := range StorefrontTable {
		if info.CountryCode == code {
			return info.StorefrontID
		}
	}
	return 0
}

var SupportedLanguageTagsMap = map[string][]string{
	"dz": {"en-GB", "fr-FR", "ar"},
	"ao": {"en-GB"},
	"ai": {"en-GB"},
	"ag": {"en-GB"},
	"ar": {"es-MX", "en-GB"},
	"am": {"en-GB"},
	"au": {"en-AU", "en-GB"},
	"at": {"de-DE", "en-GB"},
	"az": {"en-GB"},
	"bs": {"en-GB"},
	"bh": {"en-GB", "ar"},
	"bb": {"en-GB"},
	"by": {"en-GB"},
	"be": {"en-GB", "fr-FR", "nl"},
	"bz": {"en-GB", "es-MX"},
	"bj": {"en-GB", "fr-FR"},
	"bm": {"en-GB"},
	"bt": {"en-GB"},
	"bo": {"es-MX", "en-GB"},
	"ba": {"en-GB", "hr"},
	"bw": {"en-GB"},
	"br": {"pt-BR", "en-GB"},
	"vg": {"en-GB"},
	"bg": {"en-GB"},
	"kh": {"en-GB", "fr-FR"},
	"cm": {"fr-FR", "en-GB"},
	"ca": {"en-CA", "fr-CA"},
	"cv": {"en-GB"},
	"ky": {"en-GB"},
	"td": {"en-GB", "fr-FR"},
	"cl": {"es-MX", "en-GB"},
	"cn": {"zh-Hans-CN", "en-GB"},
	"co": {"es-MX", "en-GB"},
	"cr": {"es-MX", "en-GB"},
	"hr": {"en-GB", "hr"},
	"cy": {"en-GB", "el", "tr"},
	"cz": {"en-GB", "cs"},
	"ci": {"fr-FR", "en-GB"},
	"cd": {"en-GB", "fr-FR"},
	"dk": {"en-GB", "da"},
	"dm": {"en-GB"},
	"do": {"es-MX", "en-GB"},
	"ec": {"es-MX", "en-GB"},
	"eg": {"en-GB", "fr-FR", "ar"},
	"sv": {"es-MX", "en-GB"},
	"ee": {"en-GB"},
	"sz": {"en-GB"},
	"fj": {"en-GB"},
	"fi": {"en-GB", "fi"},
	"fr": {"fr-FR", "en-GB"},
	"ga": {"fr-FR", "en-GB"},
	"gm": {"en-GB"},
	"ge": {"en-GB"},
	"de": {"de-DE", "en-GB"},
	"gh": {"en-GB"},
	"gr": {"en-GB", "el"},
	"gd": {"en-GB"},
	"gt": {"es-MX", "en-GB"},
	"gw": {"en-GB", "fr-FR"},
	"gy": {"en-GB", "fr-FR"},
	"hn": {"es-MX", "en-GB"},
	"hk": {"zh-Hant-HK", "en-GB", "zh-Hant-TW"},
	"hu": {"en-GB", "hu"},
	"is": {"en-GB"},
	"in": {"en-GB", "hi"},
	"id": {"en-GB", "id"},
	"iq": {"en-GB", "ar"},
	"ie": {"en-GB"},
	"il": {"en-GB", "he"},
	"it": {"it", "en-GB"},
	"jm": {"en-GB"},
	"jp": {"ja", "en-US"},
	"jo": {"en-GB", "ar"},
	"kz": {"en-GB"},
	"ke": {"en-GB"},
	"kr": {"ko", "en-GB"},
	"xk": {"en-GB"},
	"kw": {"en-GB", "ar"},
	"kg": {"en-GB"},
	"la": {"en-GB", "fr-FR"},
	"lv": {"en-GB"},
	"lb": {"en-GB", "fr-FR", "ar"},
	"lr": {"en-GB"},
	"ly": {"en-GB", "ar"},
	"lt": {"en-GB"},
	"lu": {"en-GB", "fr-FR", "de-DE"},
	"mo": {"zh-Hant-HK", "en-GB", "zh-Hant-TW"},
	"mg": {"en-GB", "fr-FR"},
	"mw": {"en-GB"},
	"my": {"en-GB", "ms"},
	"mv": {"en-GB"},
	"ml": {"en-GB", "fr-FR"},
	"mt": {"en-GB"},
	"mr": {"en-GB", "fr-FR", "ar"},
	"mu": {"en-GB", "fr-FR"},
	"mx": {"es-MX", "en-GB"},
	"fm": {"en-GB"},
	"md": {"en-GB"},
	"mn": {"en-GB"},
	"me": {"en-GB", "hr"},
	"ms": {"en-GB"},
	"ma": {"en-GB", "fr-FR", "ar"},
	"mz": {"en-GB"},
	"mm": {"en-GB"},
	"na": {"en-GB"},
	"np": {"en-GB"},
	"nl": {"nl", "en-GB"},
	"nz": {"en-AU", "en-GB"},
	"ni": {"es-MX", "en-GB"},
	"ne": {"en-GB", "fr-FR"},
	"ng": {"en-GB"},
	"mk": {"en-GB"},
	"no": {"en-GB", "nb"},
	"om": {"en-GB", "ar"},
	"pa": {"es-MX", "en-GB"},
	"pg": {"en-GB"},
	"py": {"es-MX", "en-GB"},
	"pe": {"es-MX", "en-GB"},
	"ph": {"en-GB"},
	"pl": {"en-GB", "pl"},
	"pt": {"pt-PT", "en-GB"},
	"qa": {"en-GB", "ar"},
	"cg": {"en-GB", "fr-FR"},
	"ro": {"en-GB", "ro"},
	"ru": {"ru", "en-GB", "uk"},
	"rw": {"en-GB", "fr-FR"},
	"sa": {"en-GB", "ar"},
	"sn": {"en-GB", "fr-FR"},
	"rs": {"en-GB", "hr"},
	"sc": {"en-GB", "fr-FR"},
	"sl": {"en-GB"},
	"sg": {"en-GB", "zh-Hans-CN"},
	"sk": {"en-GB", "sk"},
	"si": {"en-GB", "sl"},
	"sb": {"en-GB"},
	"za": {"en-GB"},
	"es": {"es-ES", "en-GB", "ca"},
	"lk": {"en-GB"},
	"kn": {"en-GB"},
	"lc": {"en-GB"},
	"vc": {"en-GB"},
	"sr": {"en-GB", "nl"},
	"se": {"sv", "en-GB"},
	"ch": {"de-CH", "de-DE", "en-GB", "fr-FR", "it"},
	"tw": {"zh-Hant-TW", "en-GB"},
	"tj": {"en-GB"},
	"tz": {"en-GB"},
	"th": {"en-GB", "th"},
	"to": {"en-GB"},
	"tt": {"en-GB", "fr-FR"},
	"tn": {"en-GB", "fr-FR", "ar"},
	"tm": {"en-GB"},
	"tc": {"en-GB"},
	"tr": {"en-GB", "tr"},
	"ae": {"en-GB", "ar"},
	"ug": {"en-GB"},
	"ua": {"en-GB", "uk", "ru"},
	"gb": {"en-GB"},
	"us": {"en-US", "es-MX", "ar", "ru", "zh-Hans-CN", "fr-FR", "ko", "pt-BR", "vi", "zh-Hant-TW"},
	"uy": {"en-GB", "es-MX"},
	"uz": {"en-GB"},
	"vu": {"en-GB", "fr-FR"},
	"ve": {"es-MX", "en-GB"},
	"vn": {"en-GB", "vi"},
	"ye": {"en-GB", "ar"},
	"zm": {"en-GB"},
	"zw": {"en-GB"},
}
